---
- name: Render Nginx configuration
  become: true
  template:
    src: "./templates/nginx-service.conf.j2"
    dest: "/etc/nginx/conf.d/stack-{{stack_name}}.conf"
    owner: www-data
    group: www-data
    mode: "0644"
  notify:
    - "Restart Nginx service"
