image: docker:20.10.11

services:
  - docker:dind

before_script:
  - apk add --update --no-cache openssh openssh-client
  - export SSH="ssh -l $SWARM_USER -p 22 -o StrictHostKeyChecking=no $SWARM_HOST"
  - eval $(ssh-agent -s);
  - echo "$SWARM_ID_RSA" | tr -d '\r' | ssh-add -
  - $SSH "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - echo $CI_PIPELINE_SOURCE
  
after_script:
  - $SSH "yes | docker system prune -a"

deploy_backend:
  script:
    - $SSH "docker pull $BACKEND_IMAGE"
    - $SSH "docker service update odin_backend --image=$BACKEND_IMAGE --replicas=2 --quiet"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_TYPE == "back"'
      when: always
    - when: never
  
deploy_frontend:
  script:
    - $SSH "docker pull $FRONTEND_IMAGE"
    - $SSH "docker service update odin_frontend --image=$FRONTEND_IMAGE --replicas=1 --quiet"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_TYPE == "front"'
      when: always
    - when: never
